# ChunkyBlocks Configuration
#
useBlock: true
radius: 1

# Chunkloading block check
blockType: 19
minHeight: 54
maxHeight: 74

# User-specified chunks
maxChunksPerUser: 1
chunks:
  Melonar:
    - home: {world: "example", x: 0, z: 0}
